### Author: Vaishnav Krishna P
### THE NUMPY TUTORIAL PART01
#### Source: numpy documentation

In [1]:
# Importing the nmpy modules 
import numpy as np
from numpy import pi

#### CREATING NUMPY ARRAY

In [3]:
# Numpy 1D Array 
a = np.array((1,2,3))
a

array([1, 2, 3])

In [6]:
# Numpy 2D array
b = np.array(((1,2,3),(4,5,6)))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
# Numpy 3D array creation
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[9,10,11]]])
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [ 9, 10, 11]]])

### SOME ARTIBUES OF NUMPY MODULE 
1. ndim: Number of axes or dimensions of the array.
2. shape: Dimensionality or shape of the array.
3. size: Total number of elements in the array.
4. dtype: Data type of the array elements.
5. itemsize: Size in bits of a single array element.
6. data: Buffer containing the actual elements of the array.

In [16]:
# Lets check the atributes,
print(f"ndim of c: {c.ndim}")
print(f"shape of c: {c.shape}")
print(f"Size of c: {c.size}")
print(f"dtype of c: {c.dtype}")
print(f"itemsize of c: {c.itemsize}")
print(f"data of c: {c.data}")

ndim of c: 3
shape of c: (2, 2, 3)
Size of c: 12
dtype of c: int64
itemsize of c: 8
data of c: <memory at 0x7fddab0428b0>


### SOME METHODS IN THE NUMPY MODULE
1. sum(): Returns the sum of all elements in the array.
2. max(): Returns the maximum value in the array.
3. min(): Returns the minimum value in the array.
4. dot(): Performs matrix multiplication.
5. cumsum(): Returns the cumulative sum of elements along a given axis.
6. sin(), cos(), exp(), ...: Trigonometric and exponential functions.
7. ones(): Returns a new array of given shape and type, filled with ones.
8. zeros(): Returns a new array of given shape and type, filled with zeros.
9. empty(): Returns a new array of given shape and type, without initializing entries.
10. arange(): Returns evenly spaced values within a given interval.
11. linspace(): Returns evenly spaced numbers over a specified interval.
12. reshape(): Gives a new shape to an array without changing its data.
13. type(): Returns the type of the object.

#### RESHAPE AND ARANGE

In [47]:
# Arange
x = np.arange(1,9,1)
print("Type of x: ",type(x))
x

Type of x:  <class 'numpy.ndarray'>


array([1, 2, 3, 4, 5, 6, 7, 8])

In [54]:
# reshape
x = x.reshape(4,2)
x

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [56]:
x = x.reshape(2,2,2)
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

#### SUM

In [61]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
# sum of all the elements in the array
x.sum()

21

In [63]:
# sum in row wise
print(x)
x.sum(axis=1)

[[1 2 3]
 [4 5 6]]


array([ 6, 15])

In [64]:
x.sum(axis=0) # column wise sum

array([5, 7, 9])

#### MAX

In [65]:
x.max() # Maximum element in the entire array

6

In [66]:
x.max(axis=1) # Row wise

array([3, 6])

In [68]:
x.max(axis=0) # column wise

array([4, 5, 6])

#### MIN

In [69]:
x.min()

1

In [70]:
x.min(axis=1)

array([1, 4])

In [72]:
x.min(axis=0)

array([1, 2, 3])

#### DOT

In [77]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[6,7,8],[9,10,11]])

In [78]:
# Lets perform matrix multiplication,
np.dot(a, b)

array([[ 43,  49,  55],
       [100, 115, 130],
       [157, 181, 205]])

#### CUMSUM

In [86]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
a.cumsum() 

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [83]:
a.cumsum(axis=1) # Row wise

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]])

In [85]:
a.cumsum(axis=0) # coolumn wise

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]])

#### LINSPACE

In [88]:
y = np.linspace(0,pi,10)
y

array([0.        , 0.34906585, 0.6981317 , 1.04719755, 1.3962634 ,
       1.74532925, 2.0943951 , 2.44346095, 2.7925268 , 3.14159265])

#### MATHEMATICAL FUNCTIONS

In [90]:
np.sin(y)

array([0.00000000e+00, 3.42020143e-01, 6.42787610e-01, 8.66025404e-01,
       9.84807753e-01, 9.84807753e-01, 8.66025404e-01, 6.42787610e-01,
       3.42020143e-01, 1.22464680e-16])

In [91]:
np.cos(y)

array([ 1.        ,  0.93969262,  0.76604444,  0.5       ,  0.17364818,
       -0.17364818, -0.5       , -0.76604444, -0.93969262, -1.        ])

In [94]:
np.exp(y)

array([ 1.        ,  1.41774255,  2.00999393,  2.84965391,  4.04007559,
        5.72778705,  8.1205274 , 11.51281719, 16.32221075, 23.14069263])

In [95]:
np.log(y)

/var/folders/15/6wmpjnb12xv6kx2m290xw72c0000gn/T/ipykernel_17230/3455148303.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y)


array([       -inf, -1.05249469, -0.35934751,  0.0461176 ,  0.33379967,
        0.55694322,  0.73926478,  0.89341546,  1.02694685,  1.14472989])

#### ONES,ZEROS,EMPTY

In [100]:
ones_array = np.ones((2,3), dtype="int16")
ones_array

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [103]:
zeros_array = np.zeros((3,4)) # default dtype float64
zeros_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [110]:
empty_array = np.empty((3,3), dtype="float") # used to create an array without initializing the entries of given shape and type.
empty_array

array([[2.35541534e-312, 2.14321575e-312, 2.31297541e-312],
       [2.05833592e-312, 2.56761491e-312, 2.05833592e-312],
       [2.29175545e-312, 2.14321575e-312, 1.09924046e+295]])